# Generated by Django 4.2.2 on 2023-06-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SignupModels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("memail", models.EmailField(max_length=254)),
                ("mpassword", models.CharField(max_length=20)),
            ],
        ),
    ]
