# Generated by Django 4.2.2 on 2023-06-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App1", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserModels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("memail", models.EmailField(max_length=254)),
                ("mname", models.CharField(max_length=20)),
                ("mage", models.IntegerField()),
                ("mcountry", models.CharField(max_length=20)),
                ("mphone", models.CharField(max_length=10)),
                ("mgender", models.CharField(max_length=10)),
            ],
        ),
    ]
